### PR TITLE
Added recursive portal

### PR DESCRIPTION
**Pull request by entropian**

### CODE REVIEW

**Comment by hhirsch** [comment]
Hello,
the feature looks amazing. Sadly I can not merge it into master because your branch is based on the bullet branch and it will be weeks until it is ready to be merged into master.

There is one other issue with the feature:
https://bugs.glportal.de/index.php?do=details&task_id=74

I tried to cherry pick your commits but it had conflicts in the renderer and I stopped at that point. However I pulled it as a new branch called bowen-bullet. 

Any way to resolve this is fine by me. I would not want to merge it with bullet since that is where Dorian is working on bullet integration at the moment and I don't want him to have to merge unanounced. I am open for suggestions. Worst case would mean to either wait for Dorian to approve and pull the commits or for Dorian to be done and merge them at that point.

**Comment by gravgun** [comment]
You're half there buddy....
1 recursive portal view is badly rotated

**Comment by entropian** [comment]
@gravgun 
Which map is that?

**Comment by hhirsch** [comment]
@gravgun Look at the screenshot. First map:
https://bugs.glportal.de/index.php?do=details&task_id=74

**Comment by hhirsch** [comment]
@gravgun Playing on the bullet branch I remembered one thing. Haven't you solved the substraction from the collision volume for boxes?

It is a suboptimal shape, but good enough until we fix the whole problem, no? This could put the bullet branch into a state where it can be merged with master.

**Comment by gravgun** [comment]
@hhirsch Yes collision subtraction works. Only for a single, statically-accessible axis-aligned volume as of now though, but it's definitely possible to handle multiple volumes.

And since non-90° rotated portals are broken anyway, that could do the job.

**Pull request merged**
